steps:

  - id: "Executando testes unitarios"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['test', 'raiz']
    env: ['GOPATH=.']

  - id: "Construindo imagem a partir do Dockerfile"
    name: 'gcr.io/cloud-builders/docker:19.03.8'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA']

  - id: "Enviando imagem para o Image Registry"
    name: 'gcr.io/cloud-builders/docker:19.03.8'
    args: ['push', 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA']

  - id: "Ajustando arquivo deployment do k8s"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g' k8s/deployment.yaml > k8s/deployment-new.yaml;
        cat k8s/deployment-new.yaml;

  - id: "Deploying k8s"
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/deployment-new.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-deployment'
