apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  selector:
    matchLabels:
      app: go-hpa
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
      - name: go-hpa
        image: img-app-deployment
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 8000
